version: 3.0.504.{build}

branches:
# whitelist
    only:
        - '3.0'
        - appveyor

install:
    - git submodule -q update --init

platform: x86
configuration: Debug

build:
    project: msvs\RedisServer.sln

artifacts:
    - path: msvs\Win32\$(configuration)\*.exe
